<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<RootNamespace>FalloutLauncher</RootNamespace>
		<AssemblyName>FEHLauncher</AssemblyName>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationIcon>ico.ico</ApplicationIcon>
		<ApplicationManifest>app.manifest</ApplicationManifest>

		<!-- Настройки для Single File + Self-Contained -->
		<SelfContained>true</SelfContained>
		<Version>1.2.1</Version>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<PublishSingleFile>true</PublishSingleFile>
		<IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
		<PublishTrimmed>false</PublishTrimmed>
		<DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="ico.ico" />
	</ItemGroup>

</Project>
